modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/NEZNAMY/TAB/issues"
license = "Apache License Version 2.0"

[[mods]]
modId = "tab"
version = "@version@"
displayName = "@name@"
authors = "@author@"
credits = "@credits@"
description = '''@description@'''
displayURL = "@website@"

[[dependencies.tab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.11]"
ordering = "NONE"
side = "SERVER"
