modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/NEZNAMY/TAB/issues"
license = "Apache License Version 2.0"

[[mods]]
modId = "tab"
version = "@version@"
displayName = "@name@"
authors = "@author@"
credits = "@credits@"
description = '''@description@'''
displayURL = "@website@"

[[dependencies.tab]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "SERVER"

[[dependencies.tab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.9],[1.21.10]"
ordering = "NONE"
side = "SERVER"
