#sorting type, having premium version automatically overrides sorting options from advancedconfig (if set)
#GROUPS                  = groups from config.yml, in that order
#GROUP_PERMISSIONS       = ^, but players need tab.sort.<group> permission to be considered in that group
#PLACEHOLDER_LOW_TO_HIGH = insert a numeric placeholder below, sorting from lowest value to highest
#PLACEHOLDER_HIGH_TO_LOW = ^, highest to lowest, can be used for some kind of levelling system
#PLACEHOLDER_A_TO_Z      = alphabetically by the placeholder
#GROUPS_THEN_PLACEHOLDER_HIGH_TO_LOW = primary sorting by groups, secondary by numeric placeholder (high to low)
#GROUPS_THEN_PLACEHOLDER_LOW_TO_HIGH = primary sorting by groups, secondary by numeric placeholder (low to high)
#... and more 
sorting-type: GROUPS
sorting-placeholder: "%some_level_maybe?%"

#if sorting type is set to PLACEHOLDER, list all possible outputs here in order you want them in tablist
placeholder-order:
- value1
- value2

#by default, names are sorted as A-Z _ a-z
#by disabling you will make it Aa-Zz
#this also applies for everything else, such as sorting by placeholder (factions, ..)
case-sentitive-sorting: true

#list of lines with adaptive height, in that order.
#after adding a new property you can give it to someone in config just like any other properties
unlimited-nametag-mode-dynamic-lines:
  - abovename
  - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
  - belowname
  - another
  
#lines with static height. Dynamic is using 0.22 blocks per line, starting at 0. With 3 lines, they are as: 0, 0.22, 0.44
#can also be negative, but be careful when configuring value so it won't end up inside of the player
unlimited-nametag-mode-static-lines:
  myCustomLine: 0.66


##############################################
################# SCOREBOARD #################
##############################################
#Limitations:
#1.8 - 1.12 clients: scoreboard title 32 characters, lines 30 characters
#1.13+ clients: no limits
#maximum 15 lines, client can't display more

#for bungee mode it counts as "server" instead of "world", such as disable in servers
scoreboard:
  enabled: false
  toggle-command: /sb
  #tab.togglescoreboard
  permission-required-to-toggle: false
  remember-toggle-choice: false
  #initially hidden until players run toggle command
  hidden-by-default: false
  #using 1-15 instead of 0s everywhere
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds: 
    - disabledworld
  #set to NONE to have no default scoreboard
  default-scoreboard: "admin"
  per-world:
    testworld: "twscoreboard"
  
scoreboards:
  admin:
    #if you don't want any condition, just delete this line
    #another option is "%your_placeholder%=something"
    #separate multiple conditions with a ; ("permission:my.perm;%placeholder%=test")
    display-condition: "permission:tab.scoreboard.admin"
    #if condition for player is not met, display a different scoreboard
    if-condition-not-met: scoreboard1
    title: "Admin scoreboard"
    lines:
      - "Scoreboard for people with permission"
      - "tab.scoreboard.admin"
  #scoreboard with no requirements
  scoreboard1:
    title: "Default"
    lines:
      - "Scoreboard for players"
  twscoreboard:
    title: "TestWorld"
    lines:
      - "This is scoreboard for everyone in testworld world"
#toggle messages
scoreboard-on: "&2Scoreboard enabled"
scoreboard-off: "&7Scoreboard disabled"


placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
    
  #only showing "Perfect" for exactly 20 TPS, standard output for any other value
  "%tps%":
    "20": "&aPerfect"
    
align-tabsuffix-on-the-right: false
character-width-overrides: {}
  
conditions:
  health:
    conditions:
      - "%health%<21"
      - "%health%>15"
    type: AND
    yes: "Healthy!"
    no: "Damaged!"
