# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true

  # types: GROUPS:<group1>,<group2>... , PERMISSIONS:<permission1>,<perm2>... , PLACEHOLDER:<output1>,<output2>... , PLACEHOLDER_A_TO_Z, PLACEHOLDER_Z_TO_A, PLACEHOLDER_HIGH_TO_LOW, PLACEHOLDER_LOW_TO_HIGH
  sorting-types:
    - "GROUPS:owner,admin,mod,helper,builder,vip,default"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sentitive-sorting: true
  disable-in-worlds:
    - disabledworld
  unlimited-nametag-mode:
    enabled: false
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: 0.22
    disable-in-worlds:
      - disabledworld
    dynamic-lines:
      - abovename
      - nametag #the original one, combination of tagprefix + customtagname + tagsuffix
      - belowname
      - another
    static-lines:
      myCustomLine: 0.66

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld

header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  header:
    - "&3&lServer name"
    - "&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<"
    - "&7Online players: &f%online%"
    - "&6Online staff: &e%staffonline%"
    - ""
    - "%animation:MyAnimation1%"
  footer:
    - "%animation:MyAnimation1%"
    - "%animation:time%"
    - "%animation:ping-tps%"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Visit our webpage %animation:web%"
  per-world:
    world1:
      header:
        - "an example of world with custom"
      footer:
        - "header/footer and prefix/suffix"
    world2-world3:
      header:
        - "This is a shared header for"
        - "world2 and world3"


yellow-number-in-tablist:
  enabled: true
  value: "%ping%"
  disable-in-worlds:
    - disabledworld

belowname-objective:
  enabled: false
  number: "%health%"
  text: "&câ¤"
  disable-in-worlds:
    - disabledworld

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Spectator-fix
prevent-spectator-effect:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  default-bars:
    - ServerInfo
  disable-in-worlds:
    - disabledworld
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"
    test:
      display-condition: "permission:tab.bossbar.test"
      style: PROGRESS
      color: WHITE
      progress: "100"
      text: "test"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Per-world-playerlist
per-world-playerlist:
  enabled: false
  # players with tab.staff will always see all players
  allow-bypass-permission: false
  # players in those worlds will always see all players
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Scoreboard-(premium-only)
scoreboard:
  enabled: false
  # show/hide the scoreboard
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  # when enabled, will show 0-14 in red next to lines 
  use-numbers: false
  # if use-numbers is disabled, this number will show in red next to all lines
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds: 
    - disabledworld
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%&7/&4%maxplayers%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - ""
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"
    scoreboard1:
      title: "Default"
      lines:
        - "%animation:MyAnimation1%"
        - "&6My Stats:"
        - "* &eKills&7: &f%statistic_player_kills%"
        - "* &eDeaths&7: &f%statistic_deaths%"
        - "* &eHealth&7: &f%health%"
        - ""
        - "&6Personal Info:"
        - "* &bRank&7: &f%rank%"
        - "* &bPing&7: &f%ping%&7ms"
        - "* &bWorld&7: &f%world%"
        - "%animation:MyAnimation1%"

ping-spoof:
  enabled: false
  # when enabled, all players will have this value as their ping
  value: 0

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix
fix-pet-names:
  enabled: false

# https://github.com/NEZNAMY/TAB/wiki/config.yml#placeholders
placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0
  remove-strings:
    - "[]"
    - "< >"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements-(premium-only)
placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  "%afk%":
    true: " &o[AFK]&r"
    false: ""
  "%tps%":
    "15-20": "&a%value%"
    "10-15": "&e%value%"
    "5-10": "&6%value%"
    "0-5": "&c%value%"

# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders-(premium-only)
conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"
  health:
    conditions:
      - "%health%<21"
      - "%health%>15"
    type: AND
    yes: "Healthy!"
    no: "Damaged!"

# https://github.com/NEZNAMY/TAB/wiki/Optimizing-the-plugin#3---placeholder-refresh-intervals
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

#if none of the above fits your needs, you can enable this to give groups using tab.group.<group name from the list below> permission
assign-groups-by-permissions: false

#if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password