#Owner:
#  tabprefix: "&0&l[&a&lOwner&0&l] &a"
#  tagprefix: "&2&lOwner &a"
Player:
  tabprefix: "&0&l[&7&lPlayer&0&l] &3"
  tagprefix: "&2&lPlayer &3"

 # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
  tabsuffix: "%luckperms-suffix%"
  tagsuffix: "%luckperms-suffix%"

per-world:
  world1:
    Owner:
      tabprefix: "&0&l[&a&lOwner&0&l] &a"
      tagprefix: "&2&lOwner &a"