modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/NEZNAMY/TAB/issues"
license = "Apache License Version 2.0"
displayURL = "@website@"

[[mods]]
modId = "tab"
version = "@version@"
displayName = "@name@"
authors = "@author@"
credits = "@credits@"
description = '''@description@'''

[[dependencies.tab]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "SERVER"
