# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

header-footer:
  enabled: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  header:
    - "&3&lServer name"
    - "&7&l>> %animation:Welcome%&3 &l%player%&7&l! &7&l<<"
    - "&7Online players: &f%online%"
    - "&6Online staff: &e%staffonline%"
    - ""
    - "%animation:MyAnimation1%"
  footer:
    - "%animation:MyAnimation1%"
    - "%animation:time%"
    - "&2Ping: %ping%"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "&7Visit our webpage %animation:web%"
  per-server:
    server1:
      header:
        - "an example of server with custom"
      footer:
        - "header/footer and prefix/suffix"
    server2;server3:
      header:
        - "This is a shared header for"
        - "server2 and server3"

tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
    - "GROUPS:owner,admin,mod,helper,builder,vip,default"
    - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

yellow-number-in-tablist:
  enabled: true
  value: "%ping%"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2

belowname-objective:
  enabled: false
  number: "%health%"
  text: "&cHealth"
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver

prevent-spectator-effect:
  enabled: false

bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"

scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds: 
    - disabledworld
  disable-in-servers:
    - disabledserver
  scoreboards:
    admin:
      # Only players with tab.scoreboard.admin can see this scoreboard, others will see scoreboard1
      display-condition: "permission:tab.scoreboard.admin"
      title: "Admin scoreboard"
      lines:
        - "%animation:MyAnimation1%"
        - "&6Online:"
        - "* &eOnline&7: &f%online%&7/&4%maxplayers%"
        - "* &eCurrent World&7: &f%worldonline%"
        - "* &eStaff&7: &f%staffonline%"
        - " "
        - "&6Server Info:"
        - "* &bTPS&7: %tps%"
        - "* &bUptime&7: &f%server_uptime%"
        - "* &bMemory&7: &f%memory-used%&7/&4%memory-max%"
        - "%animation:MyAnimation1%"
    scoreboard1:
      title: "Default"
      lines:
        - "%animation:MyAnimation1%"
        - "&6My Stats:"
        - "* &eKills&7: &f%statistic_player_kills%"
        - "* &eDeaths&7: &f%statistic_deaths%"
        - "* &eHealth&7: &f%health%"
        - " "
        - "&6Personal Info:"
        - "* &bRank&7: &f%group%"
        - "* &bPing&7: &f%ping%&7ms"
        - "* &bWorld&7: &f%world%"
        - "%animation:MyAnimation1%"

ping-spoof:
  enabled: false
  value: 0

placeholders:
  date-format: "dd.MM.yyyy"
  time-format: "[HH:mm:ss / h:mm a]"
  time-offset: 0

placeholder-output-replacements:
  "%essentials_vanished%":
    "yes": "&7| Vanished"
    "no": ""
  "%essentials_nickname%":
    "%essentials_nickname%": "%player%" # placeholder did not parse correctly, show real name instead
    
  # bukkit-only placeholders used in default groups.yml, doing this as a fix
  "%afk%":
    "%afk%": "" 
  "%vault-prefix%":
    "%vault-prefix%" : ""
  "%vault-suffix%":
    "%vault-suffix%" : ""

conditions:
  nick: # use it with %condition:nick%
    conditions:
      - "%player%=%essentials_nickname%"
    yes: "%player%"
    no: "~%essentials_nickname%"

placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 1000

#if none of the above fits your needs, you can enable this to give groups using tab.group.<group name from the list below> permission
assign-groups-by-permissions: false

#if the option above is true, all groups are taken based on permissions and the one higher in this list is used as primary
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default

debug: false

mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password

use-bukkit-permissions-manager: false